### ISSUE TITLE
User Input - User Symbol

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#10]
When I go to enter my symbol, it does not accept 'X' or 'x'.

A user would inherently choose the X or O characters over a numeric value.

**Comment by dramire83** [comment]
Working to change the original code from Int type based to Str type based due to all of the coding being affected due to any change at the base level.

**Comment by dramire83** [comment]
Have completed the goal of allowing the user to select X or O with no issues even if choosing lower case versions of the characters.
