### ISSUE TITLE
Abstraction - Playagain Logic

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#12]
You have two While loops that have similar logic and have minimal deviation between the two logic blocks.

Main Method
- do-while block

**Comment by dramire83** [comment]
Still working on trying to figure out how to consolidate the While loops without breaking the program. At the moment the program has a bug when I change the first While loop to a Do-While loop so the initial entry is always a invalid entry and the second works fine.

**Comment by dramire83** [comment]
Resolved the issue that was causing an invalid entry error on the initial entry now it works as designed.
