### ISSUE TITLE
Commits - Atomic

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#19]
Refer to #15 

Your commits are smaller than before but you need to make even smaller commits.

If you focus on one feature addition between merges up to QA and commit all those small relevant changes more often.

Make sure the commits are big enough to where your commit message can easily identify the purpose of the commit, while also being small enough to easily rollback without effecting unrelated code.

**Comment by dramire83** [comment]
Started making more relevant changes tied to each commit to allow for rollback if needed.
