### ISSUE TITLE
Code - Excessive Loop Usage

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#20]
Refer #12 

You have way too many While loops inside of your Do-While.  Loops overly used will increase your resource utilization due to their compiled design.

When you complete your application of the Separation of Concerns Design, a lot of the excess While loops should disappear.  But I am marking this in the event you are not able to complete the Abstractive Process.

**Comment by dramire83** [comment]
I have redesigned my program through the use of refactoring with the Separation of Concerns to decrease clutter.
Have executed refactoring over all methods/functions and created a better streamline Object-oriented design.
