### ISSUE TITLE
Code - @playerInput

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#22]
You need to evaluate this variables purpose and how it is being used.

You use for Decision Tree logic and also While Loop condition's.

Ask your self some questions:

- What is the purpose of the variable?
- Is its current use beyond its intended purpose?
- Would there be a better approach to leveraging the variables purpose?

When you finally get your Abstractive Design implemented, these are the questions you ask yourself to get rid of relics in your program that may no longer have a purpose.

**Comment by dramire83** [comment]
Simplified the process for the user to select "X" and "O".
