### ISSUE TITLE
Code - turnChosen method

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#25]
A simple question "Go first (y/n)?" should be applied.  If I say Yes, then it only effects the first turn of the game; if No, again only affects the first turn of the game.

Don't make your logic overly complex long-term, always challenge yourself to minimize your approach.  In other words, just because you implemented today, does not mean your married to that design tomorrow.

Also review your while loop and change it to a Do-While; since you need this to execute at least once.

For My Reference:
```
        private static int turnChosen()
        {
            Console.WriteLine(" Would you like to play first or second please enter 1 or 2.");
            validInfo = Console.ReadLine();
            isInRange = int.TryParse(validInfo, out playerTurn);
            while (!isInRange || playerTurn < 1 || playerTurn > 2)
            {
                Console.Clear();
                welcomeSign();
                playerTurn = 3;
                Console.WriteLine(" Invalid entry! ");
                Console.WriteLine(" Would you like to play first or second please enter 1 or 2.");
                validInfo = Console.ReadLine();
                isInRange = int.TryParse(validInfo, out playerTurn);
            }
            return playerTurn;
        }

```

**Comment by dramire83** [comment]
Loop logic changed to Do-While to execute for better performance.
