### ISSUE TITLE
Repository - Commits

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#29]
Ref #19 

Your commits need to be focused on "what would happen if I needed to rollback a commit", what would be the result?

In this example (image below), a rollback would remove the method "gameMenu" (New Code), just to rollback the if statement (Code Change).  Atomic Commits are solely focused on putting the code back to a previous state without losing unrelated functionality.  This example commit would have far reaching unintended consequences to the program, as a whole.

![image](https://user-images.githubusercontent.com/53241126/232900915-c216b2a3-f661-4eee-ab89-d32dee3dcabb.png)

**Comment by dramire83** [comment]
Will need to work on trying to do more micro commits. I tend to forget to commit while coding because I get so caught up in all the logic as the program is executing and errors are popping up.
