### ISSUE TITLE
Comments - Loop: Program.Main

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#32]
Each Loop should have a Single-Line Comment before the Do-While, While, For, or ForEach describing the purpose of the Loop.

The Do-While should have an additional Single-Line Comment describing what is being checked in the While Expression for it to continue; any other evaluation would necessitate a "break".

**Comment by dramire83** [comment]
Have gone through all of the loops and commented before the execution to explain what is the purpose of each block of logic.
