### ISSUE TITLE
Comments - Loop: Program.gameMenu

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#35]
Each Loop should have a Single-Line Comment before the Do-While, While, For, or ForEach describing the purpose of the Loop.

The Do-While should have an additional Single-Line Comment describing what is being checked in the While Expression for it to continue; any other evaluation would necessitate a "break".

**Comment by dramire83** [comment]
Have created better Comment lines before all loops to better explain the purpose for each logic block of execution.
