### ISSUE TITLE
Coordinate Select - No Response on Bad Input

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#4]
Not knowing what the numbers 0-8 mapped to, I entered 2 which evidently was already taken but had not response back about it being taken.

**Comment by dramire83** [comment]
I have added a clear key that will refresh as the game is played so the player will know what spaces are available. It also refreshes in real-time as the game is being played. If you type in a position already occupied by the player or computer it will also communicate that to the user.
