### ISSUE TITLE
Comments - Decision: Program.printBoard

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#43]
Decision (Switch-Case, Multiple Condition If-else and if-elseif) blocks should be Single Line Commented before the Decision Tree and it should effectively communicate the purpose of that Decision Tree before the start. Then each subsequent internal block should start with a Comment effectively communicating that path of the decision tree

**Comment by dramire83** [comment]
Have successfully executed single line comments for each decision tree.
