### ISSUE TITLE
Comments - Method: Program.welcomeSign

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#50]
Member Methods should be Multi-Line Commented, effectively communicating the purpose and intent of the Method as it pertains to the Class.  As well, the Comment block should describe the type and purpose of the Parameters and Return Value.

**Comment by dramire83** [comment]
Have created better Comment lines before all loops to better explain the purpose for each logic block of execution.
Have executed refactoring over all methods/functions and created a better streamline Object-oriented design.
