### ISSUE TITLE
Separation of concerns - Main Method

### ISSUE THREAD

**Issue by jwood36** [dramire83/CIS_285#7]
Abstract similar logic into methods of concern to minimize the supportable length of the Main method.

**Comment by dramire83** [comment]
I have implemented a new method called endGameResults() to help minimize logic typed into the Main method. I have updated and cleaned up two methods: anotherGame() and resetGameBoard() to also help to minimize the logic in the Main method. As I continue coding the requirements for the game I will be trying to simplify and add new methods to help minimize logic even more in the Main method.

**Comment by dramire83** [comment]
I have completed more formatting to the program to help clean up and try to minimize the amount of redundancy in the main method.
